CONFIG_GPIO=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_PRINTK=y

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

CONFIG_W1=y
CONFIG_SENSOR=y
CONFIG_DS18B20=y

CONFIG_SENSOR_LOG_LEVEL_DBG=y

CONFIG_ADC=y
CONFIG_ADC_ESP32=y

CONFIG_I2C=y
CONFIG_I2C_ESP32=y